/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/*
observations:
- only every third number in the Fibonacci series is even and all other numbers are odd.
- only by adding two even numbers or two odd numbers could we obtain an even number
- since we start with two odd numbers, two consecutive even numbers cannot exist 
- the only case to generate an even number is through the sum of two odd numbers.
*/

#include <iostream>
using namespace std;

int main(){
    int one = 2;
    int two = 8;
    int temp = 0;
    int sum = 0;
    while (one < 4000000){
        sum += one;
        temp = two;
        two = 4 * two + one;
        one = temp;
    }
    cout << sum;
}
